# Generated by Django 4.0.2 on 2022-02-02 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(default='sin asignar', max_length=500, verbose_name='name')),
                ('barcode', models.CharField(default='sin asignar', max_length=500, verbose_name='barcode')),
                ('stock', models.IntegerField(default=0, verbose_name='existencia')),
                ('stockMax', models.PositiveIntegerField(default=0, verbose_name='stockMaximo')),
                ('stockMin', models.PositiveIntegerField(default=0, verbose_name='stockMinimo')),
                ('pv1', models.CharField(default='Sin_asignar', max_length=100)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='im.category')),
                ('provedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scm.provider')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('values', models.CharField(max_length=100000, verbose_name='margin')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='im.product')),
            ],
            options={
                'verbose_name': 'Margin',
                'verbose_name_plural': 'Margins',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('values', models.CharField(max_length=100000)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='im.product')),
            ],
            options={
                'verbose_name': 'Cost',
                'verbose_name_plural': 'Costs',
                'ordering': ['id'],
            },
        ),
    ]
