# Generated by Django 4.0.2 on 2022-02-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0004_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=500, unique=True, verbose_name='barcode'),
        ),
    ]
