# Generated by Django 4.0.2 on 2022-02-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0006_product_costo_product_margen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pv1',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
