# Generated by Django 4.0.2 on 2022-02-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0007_alter_product_pv1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='name'),
        ),
    ]
