# Generated by Django 4.0.2 on 2022-02-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0008_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100000, unique=True, verbose_name='brand'),
        ),
    ]
