# Generated by Django 4.0.2 on 2022-02-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0012_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='margenMayoreo',
            field=models.CharField(default=0.05, max_length=100, verbose_name='margenMayoreo'),
        ),
    ]
