# Generated by Django 4.0.2 on 2022-03-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0014_product_granel_product_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='margenGranel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='margenGranel'),
        ),
    ]
