# Generated by Django 4.0.2 on 2022-03-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0015_product_margengranel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='margenGranel',
            field=models.CharField(default=0, max_length=100, verbose_name='margenGranel'),
        ),
    ]
