# Generated by Django 4.0.2 on 2022-03-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0016_alter_product_margengranel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unidad',
            field=models.CharField(choices=[(1, 'Kilo'), (2, 'pieza'), (2, 'metro')], default=2, max_length=100, verbose_name='unidad'),
        ),
    ]
