# Generated by Django 4.0.2 on 2022-03-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0017_product_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unidad',
            field=models.CharField(choices=[('kilo', 'Kilo'), ('pieza', 'pieza'), ('metro', 'metro')], default='pieza', max_length=100, verbose_name='unidad'),
        ),
    ]
