# Generated by Django 4.0.2 on 2022-03-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0018_alter_product_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unidad',
            field=models.CharField(choices=[('kilo', 'Kilo'), (2, 'pieza'), ('metro', 3)], default='pieza', max_length=100, verbose_name='unidad'),
        ),
    ]
