# Generated by Django 4.0.2 on 2022-03-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0020_alter_product_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unidad',
            field=models.CharField(choices=[('Pieza', 'pieza'), ('Kilo', 'kilo'), ('Metro', 'metro')], default='pieza', max_length=100, verbose_name='unidad'),
        ),
    ]
