# Generated by Django 4.0.2 on 2022-03-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0022_alter_product_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unidad',
        ),
    ]
