# Generated by Django 4.0.2 on 2022-03-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0023_remove_product_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unidad',
            field=models.CharField(choices=[('Pieza', 'pieza'), ('Kilo', 'kilo'), ('Metro', 'metro')], default='Pieza', max_length=100, verbose_name='unidad'),
        ),
    ]
