# Generated by Django 4.0.2 on 2022-03-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0024_product_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unidad',
            field=models.CharField(choices=[('Pieza', 'pieza'), ('Gramos', 'gramos'), ('Metro', 'metro')], default='Pieza', max_length=100, verbose_name='unidad'),
        ),
    ]
