# Generated by Django 4.0.2 on 2022-03-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0025_alter_product_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='minimo'),
        ),
    ]
