# Generated by Django 4.0.2 on 2022-03-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0026_alter_product_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unidadEmpaque',
            field=models.CharField(default='1', max_length=100, verbose_name='unidadEmpaque'),
        ),
    ]
