# Generated by Django 4.0.2 on 2022-02-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('phoneNumber', models.CharField(max_length=150, verbose_name='Phone')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ['id'],
            },
        ),
    ]
