# Generated by Django 4.0.2 on 2022-02-04 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0001_initial'),
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(default='mostrador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scm.provider')),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='purchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='im.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scm.purchase')),
            ],
            options={
                'verbose_name': 'purchaseItem',
                'verbose_name_plural': 'purchasesItems',
                'ordering': ['id'],
            },
        ),
    ]
