# Generated by Django 4.0.2 on 2022-02-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0002_purchase_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='cost',
            field=models.CharField(default=0, max_length=1000, verbose_name='cost'),
        ),
    ]
