# Generated by Django 4.0.2 on 2022-03-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0005_alter_provider_options_alter_provider_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name'], 'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
    ]
