# Generated by Django 4.0.2 on 2022-05-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0006_alter_provider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['-id'], 'verbose_name': 'purchaseItem', 'verbose_name_plural': 'purchasesItems'},
        ),
    ]
