# Generated by Django 4.0.2 on 2022-02-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tipo',
            field=models.CharField(choices=[('menudeo', 'menudeo'), ('mayoreo', 'mayoreo')], default='menudeo', max_length=150, verbose_name='Phone'),
        ),
    ]
