# Generated by Django 4.0.2 on 2022-03-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_saleitem_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
