# Generated by Django 4.0.2 on 2022-03-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='margen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
