# Generated by Django 4.0.2 on 2022-03-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_saleitem_margen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['-id'], 'verbose_name': 'saleItem', 'verbose_name_plural': 'salesItems'},
        ),
    ]
