# Generated by Django 4.0.2 on 2022-03-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_saleitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['date_created'], 'verbose_name': 'sale', 'verbose_name_plural': 'sales'},
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
