# Generated by Django 4.0.2 on 2022-03-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_sale_options_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='margen',
            field=models.CharField(default=0, max_length=100, verbose_name='margen'),
        ),
    ]
