# Generated by Django 4.0.2 on 2022-05-19 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0027_product_unidadempaque'),
        ('crm', '0012_devolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='devolutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default=0, max_length=50)),
                ('cost', models.CharField(blank=True, max_length=50, null=True)),
                ('margen', models.CharField(default=0, max_length=100, verbose_name='margen')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('devolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.devolution')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='im.product')),
            ],
            options={
                'verbose_name': 'devolutionItem',
                'verbose_name_plural': 'devolutionsItems',
                'ordering': ['-id'],
            },
        ),
    ]
