# Generated by Django 4.0.2 on 2022-06-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_devolutionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='monedero',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
