# Generated by Django 4.0.2 on 2022-06-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_client_monedero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tipo',
            field=models.CharField(choices=[('sin Monedero', 'sin Monedero'), ('con Monedero', 'con Monedero')], default='sin Monedero', max_length=100),
        ),
    ]
