# Generated by Django 4.0.2 on 2022-06-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_sale_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='monedero',
            field=models.BooleanField(default=False),
        ),
    ]
