# Generated by Django 4.0.2 on 2022-06-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_sale_monedero'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='monedero',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
