# Generated by Django 4.0.2 on 2022-06-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_saleitem_monedero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='monedero',
            new_name='monederoSaleItem',
        ),
    ]
