# Generated by Django 4.0.2 on 2022-06-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_rename_monedero_saleitem_monederosaleitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='monederoSaleItem',
            new_name='monedero',
        ),
    ]
