# Generated by Django 4.0.2 on 2022-06-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_saleitem_monedero'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolution',
            name='monedero',
            field=models.BooleanField(default=False),
        ),
    ]
